# Website Settings
title: Operating Systems
titleshort: OS
titlenum: CSCI 460
lectures: "Barnard Hall 108 | Monday, Wednesday, Friday 8:00–8:50 a.m."
officehours: "NAH 253A | Monday, Wednesday, Friday 9:00&ndash;10:00 a.m. and by appointment."
term: Fall 2019
textbook: "Operating Systems: Internals and Design Principles (9th Edition), by William Stallings"
textbooklink: "[(Amazon)](https://www.amazon.com/Operating-Systems-Internals-Design-Principles/dp/0134670957)"
url: https://traviswpeters.github.io/cs460/
baseurl:
instructor: Dr. Travis Peters
img: assets/peters-sq.png
office: NAH 253A
email: travis.peters1@montana.edu
d2l: https://ecat.montana.edu/d2l/home/553509
questionnaire: "[Questionnaire](https://forms.gle/Krmco3bNsbPRjSca7)"
