# Website Settings
# site.data.settings.XXXXXXXXX
title: Operating Systems
titleshort: OS 460
titlenum: CSCI 460
school: Montana State University
term: Fall 2019
lectures: "Barnard Hall 108 | Monday, Wednesday, Friday 8:00–8:50 a.m."
officehours: "NAH 253A | Monday, Wednesday, Friday 9:00&ndash;10:00 a.m. and by appointment."
textbook: "Operating Systems: Internals and Design Principles (9th Edition), by William Stallings"
textbooklink: "[(Amazon)](https://www.amazon.com/Operating-Systems-Internals-Design-Principles/dp/0134670957)"
instructor: Dr. Travis Peters
img: assets/peters-sq.png
url: https://traviswpeters.github.io/cs460/
baseurl:
office: NAH 253A
officephone: "x4296" # extension
email: travis.peters1@montana.edu
d2l: https://ecat.montana.edu/d2l/home/553509

# locations of things (notes, slides, etc.)
slides: "notes"
notes: "notes"
solutions: "solutions"
code: "code"
reading: "notes"
exams: "notes"

menu:
# - {name: 'Syllabus', url: '#'}
- {name: 'Schedule', url: '#schedule'}
- {name: 'Code', url: 'code'}
- {name: 'Assignments', url: '#assignments'}
- {name: 'Exams', url: '#exams'}
- {name: 'Project', url: 'project'}
# - {name: 'Assignments', url: 'lab/lab_assignments'}

assignments:
- {name: 'Programming Assignment 1: Concurrency', url: 'a1'}
# - {name: 'Programming Assignment 2: XYZ', url: 'a2'}
# - {name: 'Programming Assignment 3: XYZ', url: 'a3'}
