# Website Settings
# site.data.settings.XXXXXXXXX
title: Operating Systems
titleshort: OS 460
titlenum: CS 460 #CSCI 460
titlenumshort: CS 460
school: Montana State University
term: Fall 2019
lectures: "Barnard Hall 108 | Monday, Wednesday, Friday 8:00–8:50 a.m."
officehours: "NAH 253A | Monday, Wednesday, Friday 9:00&ndash;10:00 a.m. and by appointment."
textbook: "Operating Systems: Internals and Design Principles (9th Edition), by William Stallings"
textbooklink: "[(Amazon)](https://www.amazon.com/Operating-Systems-Internals-Design-Principles/dp/0134670957)"
instructor: Dr. Travis Peters
img: assets/peters-sq.png
url: https://traviswpeters.github.io/cs460/
baseurl:
office: NAH 253A
officephone: "x4296" # extension
email: travis.peters1@montana.edu
d2l: https://ecat.montana.edu/d2l/home/553509

# locations of things (notes, slides, etc.)
slides: "notes"
notes: "notes"
solutions: "solutions"
code: "code"
reading: "notes"
exams: "notes"

menu:
# - {name: 'Syllabus', url: '#'}
- {name: 'Schedule', url: '#schedule'}
- {name: 'Assignments', url: '#assignments'}
- {name: 'Exams', url: '#exams'}
- {name: 'Project', url: 'project'}
# - {name: 'Code', url: 'code'}

homeworks:
  hw1:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW1'
    due: 'Due 09/13'
    show: True
  hw2:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW2'
    due: 'Due 10/11'
    show: True
  hw3:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW3'
    due: 'Due 10/18'
    show: True
  hw4:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW4'
    due: 'Due 10/25'
    show: True
  hw5:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW5'
    due: 'Due 11/01'
    show: False
  hw6:
    url: 'https://ecat.montana.edu/d2l/home/553509'
    shortname: 'HW6'
    due: 'Due 11/08'
    show: False

assignments:
  a1:
    shortname: 'PA1'
    longname: 'Programming Assignment 1: Concurrency'
    url: 'a1'
    due: 'Due 10/16'
    timedue: '@10pm'
    show: True
  a2:
    shortname: 'PA2'
    longname: 'Programming Assignment 2: Scheduling'
    url: 'a2'
    due: 'Due 11/08'
    tinedue: '@10pm'
    duelong: 'Friday, November 8th, 2019 @10pm'
    show: False
  a3:
    shortname: 'PA3'
    longname: 'Programming Assignment 3: ???'
    url: 'a3'
    due: 'Due 11/22'
    tinedue: '@10pm'
    show: False

# exams:
# - {name: 'Exam 1', url: 'exam1'}
